### ISSUE TITLE
No module named flask.ext.cors

### ISSUE THREAD

**Issue by cuongduc** [maxpumperla/betago#1] opened 2016-04-15 05:17 UTC
When I tried to run `python run_demo.py` I got the following error (even though I have installed Flask)

```
Traceback (most recent call last):
  File "run_demo.py", line 7, in <module>
    from betago.model import KerasBot
  File "/home/taylor/Code/betago/betago/model.py", line 3, in <module>
    from flask.ext.cors import CORS, cross_origin
  File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.cors
```

**Comment by tarriel** [comment] 2016-04-15 06:02
I had to go 
sudo pip install -U flask
sudo pip install -U flask-cors
sudo pip install -U future 

now I have the error 

```
Using Theano backend.
Traceback (most recent call last):
  File "run_demo.py", line 8, in <module>
    from betago.dataloader.processor import SevenPlaneProcessor
ImportError: No module named processor
```

**Comment by heiguo** [comment] 2016-04-15 06:08
@tarriel I edited run_demo.py, changed '`from betago.dataloader.processor`' into '`from betago.processor`'

now the error is:
`
Using Theano backend.
Traceback (most recent call last):
  File "run_demo.py", line 18, in <module>
    model = model_from_yaml(yaml.dump(yml))
  File "/Library/Python/2.7/site-packages/keras/models.py", line 19, in model_from_yaml
    return layer_from_config(config, custom_objects=custom_objects)
  File "/Library/Python/2.7/site-packages/keras/utils/layer_utils.py", line 24, in layer_from_config
    class_name = config['class_name']
KeyError: 'class_name'
`

**Comment by maxpumperla** [comment] 2016-04-15 06:17
Thanks for the feedback, working on it right now. 

@cuongduc I'll have to add flask and friends to dependencies, maybe get rid of CORS after all

@tarriel yes, @heiguo is right, I moved processor one submodule up. I will quickly fix this.

@heiguo thank you for this. The reason for this is that I created the model zoo with Keras 0.3 and suggest to use 1.0 now. There seems to be a backward incompatibility in serialization. Let me see if I can quickly port this and get back to you.

**Comment by maxpumperla** [comment] 2016-04-15 06:59
@cuongduc @tarriel @heiguo I think I fixed your issues, it's on master. Can anyone confirm it's running now? 

git pull
python setup.py install
python run_demo.py

In that case I make a new release.

**Comment by maxpumperla** [comment] 2016-04-15 07:46
OK guys, I found the time to fix the issue, test them on another machine and made a new release, 0.1.
I hope this works for you and I'm really glad you reported these issues.

**Comment by cuongduc** [comment] 2016-04-15 08:07
@maxpumperla Hi, I've pulled the latest release. The flask error has gone, but now I've got:

```
Using Theano backend.
Traceback (most recent call last):
  File "run_demo.py", line 6, in <module>
    from keras.models import model_from_yaml
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 5, in <module>
    from . import backend as K
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 51, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 4, in <module>
    from theano.tensor.signal import pool
ImportError: cannot import name pool
```
I hope it will be fixed soon.
Thanks for interesting repo on Go :-)

**Comment by maxpumperla** [comment] 2016-04-15 08:12
Thanks @cuongduc, what you posted looks like a Theano error. I do not use ```theano.tensor.signal.pool``` anywhere directly and I can't reproduce your error right now

**Comment by heiguo** [comment] 2016-04-15 08:52
@maxpumperla thx. ok to run now.

**Comment by maxpumperla** [comment] 2016-04-15 16:02
@cuongduc @tarriel any feedback, guys? Are we good?

**Comment by maxpumperla** [comment] 2016-04-17 15:30
Guys, I'd propose to close this issue. If something comes up, just reopen it again. Thanks.

**Closed by maxpumperla** 2016-04-17 15:30 UTC

**Comment by rocketinventor** [comment] 2016-05-20 14:02
I just downloaded the latest version and I'm having this problem.

**Comment by rocketinventor** [comment] 2016-05-20 14:08
I followed all instructions, installing from Main. Error, still:

`Using Theano backend.
Traceback (most recent call last):
  File "run_demo.py", line 7, in <module>
    from betago.model import HTTPFrontend, KerasBot
  File "/home/ubuntu/workspace/betago/betago/model.py", line 7, in <module>
    from flask.ext.cors import CORS
  File "/home/ubuntu/workspace/.betago/local/lib/python2.7/site-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.cors`
